apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx01
  name: lbsvc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # by default classic lb will be deployed to use network lb use annotations
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx01
  type: LoadBalancer
  #when creating this make sure to create a nodeport