apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx01
  name: lbsvc3
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    #can also be used another annotation for ssl certificate
    # by default classic lb will be deployed to use network lb use annotations
spec:
  ports:
    name: http
  - port: 443 # this need to be changed to 443 if use https ssl certificate
      protocol: TCP
      targetPort: 80
  - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx01
  type: LoadBalancer
  #when creating this make sure to create a nodeport

---
apiVersion: v1 # this can be used mostly for external databases
kind: Service
metadata:
  name: my-service
spec:
  type: ExternalName
  externalName: my.database.example.com #here we can use dns name

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx01
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 142.250.189.174  #this is used for external ips instead of dns or hostnames

---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
subsets:
  - addresses:
      - ip: 142.250.189.174
    ports:
      - port: 80
        name: my-service

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: nginx
  servicename: "nginx"
  replicas: 3
  template:
    metadata:
      lables:
        app: nginx
spec:
  containers:
  - name: nginx
    image: sreeharshav/rollingupdate:v5
    ports:
    - containerPort: 80
