apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx01
  name: nodeportsvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31113 # This can be changed from 30000 to 32767 
  selector:
    app: nginx01
  type: NodePort