apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx01
  name: nginx01
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 # it will wait for 30 sec and terminates pods and moves slows every 30secs
      maxUnavailable: 0  #when we give here then it will create more 2 extra and terminate 2 after 30sec then totally extra pods will be created
  replicas: 10
  selector:
    matchLabels:
      app: nginx01
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx01
    spec:
      containers:
      - image: sreeharshav/rollingupdate:v1
        name: rollingupdate
