---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx-deployment 
  labels:
    app: nginx 
spec:
  replicas: 3 
  selector: 
    matchLabels:
      app: nginx
  template: 
    metadata: 
      labels:
        app: nginx 
    spec:
      containers: 
      - name: nginx
        image: sreeharshav/testcontainer:v1 
        ports: 
        - containerPort: 80
        readinessProbe:
           initialDelaySeconds: 30 
           periodSeconds: 5 
           timeoutSeconds: 10 
           successThreshold: 1 
           failureThreshold: 3 
           httpGet:
               path: / 
               port: 80
        livenessProbe:
           initialDelaySeconds: 60 ##  delay for first time when pod starts to transfer the traffic to application
           periodSeconds: 5 ## time to check every 5 secs whether pod is alive and ready
           timeoutSeconds: 10 ## timeout when not reachable
           successThreshold: 1 
           failureThreshold: 1
               #exec:
                  #command:
                # - cat 
                # - /var/www/html/index.html
               #tcpSocket:
                   #port: 80 
           httpGet:
               path: / 
               port: 80
---
kind: Service 
apiVersion: v1 
metadata:
  name: myservice 
  labels:
    app: nginx 
spec: 
  selector:
    app: nginx 
  type: NodePort 
  ports: 
  - name: name-of-the-port
    port: 8000 
    targetPort: 80
    nodePort: 31111