apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx001
  name: nginx001
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx001
  template:
    metadata:
      labels:
        app: nginx001
    spec:
      containers:
      - image: nginx:latest
        name: rollingupdate
      tolerations:
         - key: "perf"
           operator: "Equal"
           value: "high"
           effect: "NoSchedule"