---
apiVersion: v1 
kind: Pod 
metadata:
  name: adapter-container-demo 
  labels:
    env: prod 
spec:
  initContainers: 
  - name: init-container
    image: alpine/git 
    command: ["/bin/sh"] 
    args: ["-c", "git clone https://github.com/mavrick202/dockertesti.git /html"] 
    volumeMounts: 
    - name: nginxvol
      mountPath: /html/ 
  containers: 
  - name: adapter-container
    image: busybox:1.28 
    command: ["/bin/sh"] 
    args: ["-", "while true; do echo \\<h1\\>$(date)\\</hi\\> >> /html/index.html; sleep 5;done"] 
    volumeMounts: 
    - name: nginxvol
      mountPath: /html/ 
  - image: nginx:latest 
    name: main-container 
    imagePullPolicy: Always 
    ports:
      - containerPort: 80 
    volumeMounts: 
    - name: nginxvol
      mountPath: /usr/share/nginx/html/ 
  dnsPolicy: Default 
  volumes: 
  - name: nginxvol
    emptyDir: {}

---
apiVersion: v1 
kind: Service 
metadata:
  creationTimestamp: null 
  labels:
    env: prod 
  name: adapter-container-demo 
spec:
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 80 
  selector:
    env: prod 
  type: NodePort