---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
StringData:
  credentials:
  [default]
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
#we can also create this secret as configmaps

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx01
  name: nginx01
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx01
  template:
    metadata:
      labels:
        app: nginx01
    spec:
      containers:
        - name: anycontainername
          image:  registry/user/image
          volumeMounts:
            - name:  Name of the Volume
              mountPath:  Path to mount #/root/.aws/credentials, where the aws cred are stored.
              subPath: credentials
      volumes:
        - name:  name of the volume
          secret:
            secretName: mysecret # name of secret which was created above
