#echo -n 'iiasbjabkkoash' | base64
#echo -n 'asbkjjbsakjabckjabkj' |  base64
#first convert secret as base64 and mention in secret yml file

#you can also decode the kubernetes secrets with decode command of base64

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  username: jhabakjaj
  password: anfan

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: mycontainer
      image: redis
      env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password