---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nginx-deployment 
  labels:
    app: nginx 
spec:
  replicas: 3 
  selector: 
    matchLabels:
      app: nginx 
  template: 
    metadata: 
      labels:
        app: nginx 
    spec:
      containers: 
      - name: utils
        image: sreeharshav/utils:latest 
        volumeMounts: 
          - name: myemptydir
            mountPath: /etc/myemptydir 
          - name: containerdsock
            mountPath: "/run/containerd/ containerd.sock" 
      - name: nginx
        image: nginx 
        ports: 
        - containerPort: 80 
        volumeMounts:
            - mountPath: /tmp/myemptydir
              name: myemptydir 
      volumes: 
        - name: myemptydir
          emptyDir: {} 
        - name: containerdsock 
          hostPath:
            path: /run/containerd/containerd.sock