---
apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: aws-pv1
  labels:
    type: aws-pv1 
spec:
  storageclassName: gp2 
  persistentVolumeReclaimPolicy: Delete 
  capacity:
    storage: 2Gi 
  accessModes: 
  - ReadWriteOnce 
  awsElasticBlockStore:
    volumeID: vol-01deca2e377c38cco 
    fs Type: ext4
    
---
apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: aws-pv2
  labels:
    type: aws-pv2
spec:
  storageclassName: gp2 
  persistentVolumeReclaimPolicy: Delete 
  capacity:
    storage: 4Gi 
  accessModes: 
  - ReadWriteOnce 
  awsElasticBlockStore:
    volumeID: vol-01deca2e366c38cco 
    fs Type: ext4

## how many pv volu we need we can create with same file