---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim1
spec:
  storageclassName: gp2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi