apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: new-cluster-admin-role
rules:
- apiGroups: ["*"]  #we can mention req grps, res,verbs for another users, this is for admin role.
  resources: ["*"] 
  verbs: ["*"]

---
kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ClusterRole-Anand
subjects:
- kind: UserI
  name: anand
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: new-cluster-admin-role 
  apiGroup: rbac.authorization.k8s.io