apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
 namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mavrick202@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones: 
          - "shiva-devops.online"
      dns01:
        route53:
          region: us-west-1
          accessKeyID: AKIAUJPOFHQ4YU7ZTCVY
          secretAccessKeySecretRef:
            name: acme-route53
            key: secret-access-key
#we can also give multiple dns name in dnszones #